;    HookMan - System Hook Manager for TI-83+ Series.
;    Copyright (C) 2007  Andy Janata
;
;    This program is free software; you can redistribute it and/or modify
;    it under the terms of the GNU General Public License as published by
;    the Free Software Foundation; either version 2 of the License, or
;    (at your option) any later version.
;
;    This program is distributed in the hope that it will be useful,
;    but WITHOUT ANY WARRANTY; without even the implied warranty of
;    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;    GNU General Public License for more details.
;
;    You should have received a copy of the GNU General Public License along
;    with this program; if not, write to the Free Software Foundation, Inc.,
;    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
;
;	  You can contact the author via electronic mail at <ajanata@gmail.com>,
;	  or by writing to Andy Janata, 178 E. 5th St., Brewster, OH 44613 USA.




;	User interface string resources.

   ;    0123456789ABCEDF
titleHookman:
	.db "    HookMan     ",0
titleInstall:
	.db "    Install     ",0
titleAdvanced:
	.db "    Advanced    ",0
titleHelp:
	.db "      Help      ",0
	
itemUninstall:	.db "Uninstall",0
itemInstall:	.db "Install",0
itemAdvanced:	.db "Advanced",0
itemHelp			.db "Help",0
itemAbout		.db "About",0
itemExit			.db "Exit",0
itemBack			.db "Back",0

txtCopyright	.db "Copyright (",$FF,"c) '07 Andy Janata",0
	
menuNumbers:
	.db "0)",0
	.db "1)",0
	.db "2)",0
	.db "3)",0
	.db "4)",0
	.db "5)",0
	.db "6)",0
	.db "7)",0
	.db "8)",0
	.db "9)",0